In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time
import warnings
warnings.filterwarnings('ignore')

1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: 
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:
def Most_Viewed_YouTube_Wiki(url):
    
    driver=webdriver.Chrome()
    driver.get(url)
    
    wait=WebDriverWait(driver,10)
    
    #Declaring all the required variables list
    rank = []
    video_name = []
    artist = []
    views = []
    date = []
    
    #Code to locate all the rows of the required data to scrap
    table_rows=wait.until(EC.visibility_of_all_elements_located((By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr')))
    
    #Iteraring through all the rows of the 'table_rows' element
    for index,row in enumerate(table_rows):
        
        #Code to locate the column elements
        column=row.find_elements(By.XPATH,'.//td')
        
        #Appending rank in the rank list
        rank.append(index+1)
        
        #Scraping video name 
        video_name.append(column[0].text)
        
        #Scraping artist name 
        artist.append(column[1].text)
        
        #Scraping views name 
        views.append(column[2].text)
        
        #Scraping date name 
        date.append(column[3].text)
        
        
        video_name=[item.split('[')[0] for item in video_name]
        
    #Creating a DataFrame for all the scraped data
    df_most_viewed=pd.DataFrame({'Rank':rank,'Video Name':video_name,'Artist':artist,'Views (Billions)':views,'Date':date},index=range(1,len(rank)+1))
    
    #return the DataFrame
    return df_most_viewed
    
    
Most_Viewed_YouTube_Wiki('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

,Rank,Video Name,Artist,Views (Billions),Date
1,1,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,14.32,"June 17, 2016"
2,2,"""Despacito""",Luis Fonsi,8.41,"January 12, 2017"
3,3,"""Johny Johny Yes Papa""",LooLoo Kids - Nursery Rhymes and Children's Songs,6.89,"October 8, 2016"
4,4,"""Bath Song""",Cocomelon - Nursery Rhymes,6.66,"May 2, 2018"
5,5,"""Shape of You""",Ed Sheeran,6.23,"January 30, 2017"
6,6,"""See You Again""",Wiz Khalifa,6.22,"April 6, 2015"
7,7,"""Wheels on the Bus""",Cocomelon - Nursery Rhymes,6.01,"May 24, 2018"
8,8,"""Phonics Song with Two Words""",ChuChu TV Nursery Rhymes & Kids Songs,5.75,"March 6, 2014"
9,9,"""Uptown Funk""",Mark Ronson,5.18,"November 19, 2014"
10,10,"""Gangnam Style""",Psy,5.10,"July 15, 2012"
11,11,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,5.09,"February 27, 2018"
12,12,"""Dame Tu Cosita""",Ultra Records,4.59,"April 5, 2018"
13,13,"""Masha and the Bear – Recipe for Disaster""",Get Movies,4.57,"January 31, 2012"
14,14,"""Axel F""",Crazy Frog,4.45,"June 16, 2009"
15,15,"""Sugar""",Maroon 5,4.02,"January 14, 2015"
16,16,"""Baa Baa Black Sheep""",Cocomelon - Nursery Rhymes,4.01,"June 25, 2018"
17,17,"""Counting Stars""",OneRepublic,4.00,"May 31, 2013"
18,18,"""Lakdi Ki Kathi""",Jingle Toons,3.98,"June 14, 2018"
19,19,"""Roar""",Katy Perry,3.98,"September 5, 2013"
20,20,"""Waka Waka (This Time for Africa)""",Shakira,3.89,"June 4, 2010"
21,21,"""Sorry""",Justin Bieber,3.78,"October 22, 2015"
22,22,"""Shree Hanuman Chalisa""",T-Series Bhakti Sagar,3.77,"May 10, 2011"
23,23,"""Humpty the train on a fruits ride""",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.76,"January 26, 2018"
24,24,"""Thinking Out Loud""",Ed Sheeran,3.75,"October 7, 2014"
25,25,"""Perfect""",Ed Sheeran,3.70,"November 9, 2017"
26,26,"""Dark Horse""",Katy Perry,3.70,"February 20, 2014"
27,27,"""Let Her Go""",Passenger,3.64,"July 25, 2012"
28,28,"""Faded""",Alan Walker,3.60,"December 3, 2015"
29,29,"""Girls Like You""",Maroon 5,3.58,"May 31, 2018"
30,30,"""Lean On""",Major Lazer Official,3.57,"March 22, 2015"

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [3]:
def BCCI_International_Fixtures(url):
    
    driver=webdriver.Chrome()
    driver.get(url)
    
    #Declaring all the required variables list
    series_names = []
    places_of_match = []
    date_of_match = []
    time_of_match = []
    
    wait=WebDriverWait(driver,10)
    
    #Code to locate the 'Fixtures' link tab and click on it
    fixtures_link=wait.until(EC.visibility_of_element_located((By.XPATH,'//div[@id="imw-international-men"]//a[@data-event_context="header" and contains(text(),"Fixtures")]')))
    fixtures_link.click()
    time.sleep(5)
    
    #Code to locate all the match_card element which contains all the required data and assigning it to a variable
    match_card_frames=driver.find_elements(By.XPATH,'//div[@class="match-card match-card-fw match-card-up ng-scope"]')
    
    time.sleep(5)
    #Iterating through each match_card_frames elements 
    for each_match_card in match_card_frames:
        
        #Code to locate the series names element and append it to 'series_names' variable
        series=each_match_card.find_element(By.XPATH,'.//h5[@class="match-tournament-name ng-binding"]')
        series_names.append(series.text)
        
        #Code to locate the date of match element and append it to 'date_of_match' variable
        date=each_match_card.find_element(By.XPATH,'.//div[@class="match-dates ng-binding"]')
        date_of_match.append(date.text)
        
        
        #Code to locate the time of match element and append it to 'time_of_match' variable
        times=each_match_card.find_element(By.XPATH,'.//div[@class="match-time no-margin ng-binding"]')
        time_of_match.append(times.text)
        
        #Code to locate the place of match element and append it to 'place' variable
        all_location=each_match_card.find_elements(By.XPATH,'.//div[@class="match-place ng-scope"]/span')
        location=[loc.text.strip() for loc in all_location]
        complete_location=' '.join(location)
        
        places_of_match.append(complete_location)

        
    
    #Creating a DataFrame for all the scraped data
    df_bcci_match=pd.DataFrame({'Series':series_names,'Location':places_of_match,'Date':date_of_match,'Time':time_of_match},index=range(1,len(series_names)+1))
    
    #return the DataFrame
    return df_bcci_match
    
    
BCCI_International_Fixtures('https://www.bcci.tv/')

,Series,Location,Date,Time
1,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","5 JUNE, 2024",8:00 PM IST
2,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","9 JUNE, 2024",8:00 PM IST
3,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","12 JUNE, 2024",8:00 PM IST
4,ICC MENS T20 WORLD CUP 2024,"Central Broward Park & Broward County Stadium,...","15 JUNE, 2024",8:00 PM IST
5,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","6 JULY, 2024",8:00 PM IST
6,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","7 JULY, 2024",8:00 PM IST
7,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","10 JULY, 2024",8:00 PM IST
8,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","13 JULY, 2024",8:00 PM IST
9,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","14 JULY, 2024",8:00 PM IST

3. Scrape the details of State-wise GDP of India from statisticstime.com. url = http://statisticstimes.com/
You have to find following details: 

A) Rank

B) State

C) GSDP(23-24)- at current prices

D) GSDP(22-23)- at current prices

E) Share(21-22)

F) GDP($ billion)

In [4]:
def State_wise_GDP_Of_India(url):
    
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    
    driver=webdriver.Chrome(options=chrome_options)
    driver.get(url)
    
    #Declaring all the required variables list
    rank_of_states = []
    state_name = []
    gsdp_24_23 = []
    gsdp__23_22 = []
    states_shares = []
    gdp_of_states = []
   
    wait=WebDriverWait(driver,10)
    
    #Code to locate the economy tab link and move the mouse cursor to it
    economy_button_link=wait.until(EC.visibility_of_element_located((By.XPATH,'//button[@class="dropbtn" and contains(text(),"Economy")]')))
    economy_button_link.click()
    
    #Code to find the 'India' link from 'Economy' tab and move the coursor to it and click on it
    india_link = wait.until(EC.visibility_of_element_located((By.XPATH,'//div[@class="dropdown-content"]/a[@href="economy/india-statistics.php"]')))
    india_link.click()
    
    #Code to located the 'GDP of Indian states' link and click on it
    gdp_of_indian_states_link=wait.until(EC.visibility_of_element_located((By.XPATH,'//a[@href="india/indian-states-gdp.php" and contains(text(),"GDP of Indian states")]')))
    gdp_of_indian_states_link.click()
    
    
    #Code to locate all the rows of required data in the table
    gdp_table_body_row=wait.until(EC.visibility_of_all_elements_located((By.XPATH,'//table[@id="table_id"]/tbody/tr')))
    
    #Iterating through each row in a table
    for rows in gdp_table_body_row:
        
        #Locating each column in rows
        column=rows.find_elements(By.XPATH,'.//td')
        
        rank_of_states.append(column[0].text)
        state_name.append(column[1].text)
        gsdp_24_23.append(column[2].text)
        gsdp__23_22.append(column[3].text)
        states_shares.append(column[5].text)
        gdp_of_states.append(column[6].text)
        
    
    #Creating a DataFrame
    df_indian_states_gdp=pd.DataFrame({'Rank':rank_of_states,'State':state_name,'GSDP (24-23)':gsdp_24_23,'GSDP (23-22)':gsdp__23_22,'State\'s share':states_shares,'GDP':gdp_of_states},index=range(1,len(rank_of_states)+1))
    
    #Returning DataFrame
    return df_indian_states_gdp
    
    
    
State_wise_GDP_Of_India('https://www.statisticstimes.com/')

,Rank,State,GSDP (24-23),GSDP (23-22),State's share,GDP
1,1,Maharashtra,-,-,13.17%,414.928
2,2,Tamil Nadu,"2,700,109","2,364,514",8.78%,276.522
3,3,Karnataka,"2,500,733","2,269,995",8.38%,264.080
4,4,Uttar Pradesh,"2,547,861","2,258,040",8.37%,263.747
5,5,Gujarat,-,"2,230,609",8.17%,257.484
6,6,West Bengal,"1,700,939","1,531,758",5.63%,177.456
7,7,Rajasthan,"1,524,030","1,365,849",5.06%,159.334
8,8,Andhra Pradesh,"1,439,674","1,303,524",4.87%,153.324
9,9,Telangana,"1,463,960","1,308,034",4.76%,150.084
10,10,Madhya Pradesh,"1,363,327","1,246,471",4.63%,145.913
11,11,Kerala,-,"1,046,188",3.96%,124.764
12,12,Delhi,"1,107,746","1,014,688",3.73%,117.660
13,13,Haryana,"1,095,535","984,055",3.68%,116.001
14,14,Odisha,"832,790","753,177",2.81%,88.497
15,15,Bihar,-,"751,396",2.76%,86.817
16,16,Punjab,"736,423","676,164",2.62%,82.397
17,17,Assam,"565,401","493,167",1.74%,54.930
18,18,Chhattisgarh,"505,887","464,399",1.74%,54.806
19,19,Jharkhand,-,"393,722",1.52%,47.909
20,20,Uttarakhand,"346,206","303,781",1.13%,35.664
21,21,Jammu & Kashmir,"246,465","224,226",0.82%,25.813
22,22,Himachal Pradesh,"207,430","191,728",0.73%,22.984
23,23,Goa,-,"93,672",0.36%,11.250
24,24,Tripura,-,"72,636",0.27%,8.351
25,25,Chandigarh,-,"54,285",0.20%,6.154
26,26,Puducherry,-,"49,643",0.19%,5.849
27,27,Meghalaya,"47,381","42,697",0.16%,5.178
28,28,Sikkim,-,"42,756",0.16%,5.014
29,29,Manipur,-,-,0.16%,4.885
30,30,Arunachal Pradesh,-,"39,630",0.15%,4.643
31,31,Nagaland,-,"35,643",0.13%,4.144
32,32,Mizoram,-,-,0.12%,3.715
33,33,Andaman & Nicobar Islands,-,-,0.04%,1.385

4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [5]:
def Github_Trending_Repositories(url):
    
    
    driver=webdriver.Chrome()
    driver.get(url)
    
    #Declaring all the required variables list
    repository_title = []
    repository_description = []
    repository_urls = []
    contributors_count = []
    language_used = []
   
    
    wait=WebDriverWait(driver,10)
    
    #Locate 'Open Source' element tab link and click on it
    open_source_tab=wait.until(EC.visibility_of_element_located((By.XPATH, '//button[@type="button" and contains(text(),"Open Source")]')))
    open_source_tab.click()
    
    #Locate 'Trending' element link and click on it
    trending_repository_link=wait.until(EC.visibility_of_element_located((By.XPATH, '//a[contains(text(),"Trending")]')))
    trending_repository_link.click()
    
    #Code to find elements where all the elements are present and assigning it to a variable 'trending_repository_frames'
    trending_repository_frames=wait.until(EC.visibility_of_all_elements_located((By.XPATH,'//article[@class="Box-row"]')))
    
    #Iterating through each trending_repository_frames
    for each_frame in trending_repository_frames:
        
        #Locate the title element and append it to repository_title variable
        title=each_frame.find_element(By.XPATH,'.//h2[@class="h3 lh-condensed"]/a')
        repository_title.append(title.text.strip())
        
        #Locate the description element and append it to repository_description variable under try...except block
        try:
            description=each_frame.find_element(By.XPATH,'.//p[@class="col-9 color-fg-muted my-1 pr-4"]')
            repository_description.append(description.text)
        except NoSuchElementException:
            repository_description.append('-')
        
        #Locate the url element and append it to repository_urls variable
        url_element=each_frame.find_element(By.XPATH,'.//h2[@class="h3 lh-condensed"]/a')
        repository_urls.append(url_element.get_attribute('href'))
    
    #Iterate through all the repository_urls
    for urls in repository_urls:
        
        #Load each url in the browsers
        driver.get(urls)
        
        #Locate the contributors count element and append it to contributors_count variable under try...except block
        try:
            contributors = driver.find_element(By.XPATH,'//h2[@class="h4 mb-3"]/a[contains(text(),"Contributors")]/span[@class="Counter ml-1"]')
            contributors_count.append(contributors.text)
        except NoSuchElementException:
            contributors_count.append('-')
        
        #Locate the language used element and append it to language_used variable under try...except block
        try:
            languages=driver.find_elements(By.XPATH,'//div[@class="BorderGrid-cell"]/ul/li[@class="d-inline"]/a/span[@class="color-fg-default text-bold mr-1"]')
            language=[lang.text.strip() for lang in languages]
            lang=', '.join(language)
            language_used.append(lang)
        except NoSuchElementException:
            language_used.append('-')
       
    
    #Creating a DataFrame
    df_Github_Trending_Repositories=pd.DataFrame({'Title':repository_title,'Description':repository_description,'No. of contributors':contributors_count,'Language':language_used},index=range(1,len(repository_title)+1))
    
    #Returning a DataFrame
    return df_Github_Trending_Repositories

    
Github_Trending_Repositories('https://github.com/')

,Title,Description,No. of contributors,Language
1,princeton-nlp / SWE-agent,SWE-agent: Agent Computer Interfaces Enable So...,11,"Python, Shell, CSS, JavaScript"
2,zyronon / douyin,TikTok 抖音 Vue.js,7,"Vue, JavaScript, Less"
3,wandb / openui,OpenUI let's you describe UI using your imagin...,7,"TypeScript, Python, HTML, CSS, JavaScript, Doc..."
4,netease-youdao / QAnything,Question and Answer based on Anything.,12,"Python, Vue, Shell, TypeScript, SCSS, Dockerfile"
5,intel-analytics / ipex-llm,Accelerate local LLM inference and finetuning ...,95,"Python, Shell"
6,infiniflow / ragflow,RAGFlow is an open-source RAG (Retrieval-Augme...,11,"Python, TypeScript, Less"
7,usebruno / bruno,Opensource IDE For Exploring and Testing Api's...,170,"JavaScript, HTML, TypeScript"
8,amlweems / xzbot,"notes, honeypot, and exploit demo for the xz b...",-,"Go, Python"
9,rocketseat-education / nlw-unite-nodejs,Back-end em Node.js desenvolvido durante o NLW...,-,TypeScript
10,HardhatChad / ore,-,-,Rust
11,pedroslopez / whatsapp-web.js,A WhatsApp client library for NodeJS that conn...,98,"JavaScript, Shell"
12,microsoft / generative-ai-for-beginners,"18 Lessons, Get Started Building with Generati...",54,"Jupyter Notebook, Python, TypeScript"
13,ixartz / SaaS-Boilerplate,🚀🎉📚 SaaS Boilerplate built with Next.js + Tail...,4,"TypeScript, JavaScript, CSS, Shell"
14,PKUFlyingPig / cs-self-learning,计算机自学指南,118,HTML
15,heyform / heyform,HeyForm is an open-source form builder that al...,6,"TypeScript, SCSS"
16,HeyPuter / puter,"🌐 The Internet OS! Free, Open-Source, and Self...",33,"JavaScript, CSS, HTML"
17,atherosai / ui,Simple UI examples from my social media,3,"HTML, CSS, JavaScript, TypeScript, SCSS"
18,gethomepage / homepage,A highly customizable homepage (or startpage /...,310,"JavaScript, CSS"
19,OneUptime / oneuptime,OneUptime is the complete open-source observab...,72,"TypeScript, EJS, CSS, Handlebars, Shell, JavaS..."
20,OpenBMB / ChatDev,Create Customized Software using Natural Langu...,49,"Shell, Python, JavaScript, CSS, HTML, Dockerfile"
21,airbnb / javascript,JavaScript Style Guide,499,JavaScript
22,apache / superset,Apache Superset is a Data Visualization and Da...,"1,062","TypeScript, Python, JavaScript, HTML, Less, Shell"
23,actions / runner-images,GitHub Actions runner images,272,"PowerShell, Shell, HCL, Ruby, Python, Swift, A..."
24,firebase / firebase-ios-sdk,Firebase SDK for Apple App Development,221,"Objective-C, C++, Swift, Objective-C++, C, Ruby"
25,jwasham / coding-interview-university,A complete computer science study plan to beco...,305,

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

In [6]:
def Billboard_top_100(url):
    
    driver=webdriver.Chrome()
    driver.get(url)
    
    #Declaring all the required variables list
    song_name = []
    artist_name = []
    last_week_rank = []
    peak_rank = []
    weeks_on_board = []
   
    
    wait=WebDriverWait(driver,10)
    
    #Locate 'Billboard Hot 100' tab link and click on it
    billboard_hot_100=wait.until(EC.visibility_of_element_located((By.XPATH,'//li[@class="o-nav__list-item "]/a[contains(text(),"Billboard Hot 100")]')))
    billboard_hot_100.click()
    
    #Code will locate all the table rows
    table_rows=wait.until(EC.visibility_of_all_elements_located((By.XPATH,'//div[@class="o-chart-results-list-row-container"]')))
    
    #Iterating through each row 
    for rows in table_rows:
        
        #Code to locate the song name element and append it to variable song_name
        song=rows.find_element(By.XPATH,'.//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/h3')
        song_name.append(song.text)
        
        #Code to locate the artist name element and append it to variable artist_name
        name=rows.find_element(By.XPATH,'.//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/h3/following-sibling::span')
        artist_name.append(name.text)
        
        #Code to locate the 'Last week rank' element and append it to variable last_week_rank
        l_w_rank=rows.find_element(By.XPATH,'.//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li[4]/span')
        last_week_rank.append(l_w_rank.text)
        
        #Code to locate the 'Peek rank' element and append it to variable peak_rank
        p_rank=rows.find_element(By.XPATH,'.//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li[5]/span')
        peak_rank.append(p_rank.text)
        
        #Code to locate the 'Weeks on board' element and append it to variable weeks_on_board
        w_on_board=rows.find_element(By.XPATH,'.//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li[6]/span')
        weeks_on_board.append(w_on_board.text)
        
        
    #Creating DataFrame    
    df_billboard_top_100=pd.DataFrame({'Songs':song_name,'Artist\'s Name':artist_name,'Last week':last_week_rank,'Peak position':peak_rank,'Weeks on chart':weeks_on_board},index=range(1,len(song_name)+1))
    
    #Return the DataFrame
    return df_billboard_top_100    
        
        
Billboard_top_100('https://www.billboard.com/')

,Songs,Artist's Name,Last week,Peak position,Weeks on chart
1,Like That,"Future, Metro Boomin & Kendrick Lamar",-,1,1
2,Type Shit,"Future, Metro Boomin, Travis Scott & Playboi C...",-,2,1
3,Beautiful Things,Benson Boone,2,2,10
4,Lose Control,Teddy Swims,1,1,33
5,Too Sweet,Hozier,-,5,1
...,...,...,...,...,...
96,La Victima,Xavi,77,46,15
97,Tucson Too Late,Jordan Davis,81,81,4
98,Empire Now,Hozier,-,98,1
99,Girl I've Always Been,Olivia Rodrigo,-,99,1
100,Outskirts,Sam Hunt,92,92,3

6. Scrape the details of Highest selling novels.

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [7]:
def Highest_Selling_Novels(url):
    
    
    driver=webdriver.Chrome()
    driver.get(url)
    
    #Declaring all the required variables list
    rank = []
    book_name = []
    author_name = []
    volumes_sold = []
    publisher = []
    genre = []
   
    
    wait=WebDriverWait(driver,10)
    
    #Code to locate the table rows
    table_rows=wait.until(EC.visibility_of_all_elements_located((By.XPATH,'//table[@class="in-article sortable"]/tbody/tr')))
    
    #Iterating through each rows
    for rows in table_rows:
        
        #Locate all the column elements
        columns=rows.find_elements(By.XPATH,'.//td')
        
        rank.append(columns[0].text)
        book_name.append(columns[1].text)
        author_name.append(columns[2].text)
        volumes_sold.append(columns[3].text)
        publisher.append(columns[4].text)
        genre.append(columns[5].text)
        
    #Creating a DataFrame
    df_highest_selling_novels=pd.DataFrame({'Rank':rank,'Title':book_name,'Author':author_name,'Volume sales':volumes_sold,'Publisher':publisher,'Genre':genre},index=range(1,len(rank)+1))
    
    #Returning a DataFrame
    return df_highest_selling_novels
    
Highest_Selling_Novels('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

,Rank,Title,Author,Volume sales,Publisher,Genre
1,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
2,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
3,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
4,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
5,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
96,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
97,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
98,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
99,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
100,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

8. Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/ You have to find the following details:
        
A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute 

G) Year

In [8]:
def UCI_Machine_Learning_Repositories(url):
    
    driver=webdriver.Chrome()
    driver.get(url)
    
    #Declaring all the required variables list
    dataset_name = []
    data_type = []
    associated_task = []
    attribute_type = []
    no_of_instances = []
    no_of_attribute = []
    donated_year = []
    url_links = []
    
    wait=WebDriverWait(driver,10)
    
    #Locate all the url elements and assigning it to a variable urls_elements
    urls_elements=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
    
    #Iterating through each URL elements
    for urls in urls_elements:
        
        #Extract the href from url elements and append it to url_links variable
        url_links.append(urls.get_attribute("href"))
        
    
    #Iterate through each url link
    for url in url_links:
        
        #Load each url in the browser
        driver.get(url)
        
        #Locate the dataset name element and append it to dataset_name variable under try...except block
        try:
            name=driver.find_element(By.XPATH,'//h1[@class="text-3xl font-semibold text-primary-content"]')
            dataset_name.append(name.text)
        except NoSuchElementException:
            dataset_name.append('-')
        
        #Locate the data type element and append it to data_type variable under try...except block
        try:
            d_type=driver.find_element(By.XPATH,'//h1[@class="text-lg font-semibold text-primary" and contains(text(),"Dataset Characteristics")]/following-sibling::p')
            data_type.append(d_type.text)
        except NoSuchElementException:
            data_type.append('-')
        
        #Locate the associated task element and append it to associated_task variable under try...except block
        try:
            task=driver.find_element(By.XPATH,'//h1[@class="text-lg font-semibold text-primary" and contains(text(),"Associated Tasks")]/following-sibling::p')
            associated_task.append(task.text)
        except NoSuchElementException:
            associated_task.append('-')
        
        #Locate the attribute type element and append it to attribute_type variable under try...except block
        try:
            a_type=driver.find_element(By.XPATH,'//h1[@class="text-lg font-semibold text-primary" and contains(text(),"Feature Type")]/following-sibling::p')
            attribute_type.append(a_type.text)
        except NoSuchElementException:
            attribute_type.append('-')
        
        #Locate the instances element and append it to no_of_instances variable under try...except block
        try:
            n_of_instance=driver.find_element(By.XPATH,'//h1[@class="text-lg font-semibold text-primary" and contains(text(),"Instances")]/following-sibling::p')
            no_of_instances.append(n_of_instance.text)
        except NoSuchElementException:    
            no_of_instances.append('-')
        
        #Locate the Features element and append it to no_of_attribute variable under try...except block
        try:
            n_of_attribute=driver.find_element(By.XPATH,'//h1[@class="text-lg font-semibold text-primary" and contains(text(),"Features")]/following-sibling::p')
            no_of_attribute.append(n_of_attribute.text)
        except NoSuchElementException:
            no_of_attribute.append('-')
        
        #Locate the donated year element and append it to donated_year variable under try...except block
        try:    
            year=driver.find_element(By.XPATH,'//h2[@class="text-sm text-primary-content"]')
            donated_year.append(year.text)
        except NoSuchElementException:
            donated_year.append('-')
    
    #Creating a DataFrame and assigning it to a variable df_ml_repo
    df_ml_repo=pd.DataFrame({'Dataset Name':dataset_name,
                            'Data Type':data_type,
                            'Associated Tasks':associated_task,
                            'Feature Type':attribute_type,
                            'Instance':no_of_instances,
                            'Features':no_of_attribute,
                            'Donated Year':donated_year},index=range(1,len(dataset_name)+1))
    
    #Return DataFrame
    return df_ml_repo



UCI_Machine_Learning_Repositories('https://archive.ics.uci.edu/')

,Dataset Name,Data Type,Associated Tasks,Feature Type,Instance,Features,Donated Year
1,Iris,Tabular,Classification,Real,150,4,Donated on 6/30/1988
2,Dry Bean,Multivariate,Classification,"Integer, Real",13611,16,Donated on 9/13/2020
3,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303,13,Donated on 6/30/1988
4,Rice (Cammeo and Osmancik),Multivariate,Classification,Real,3810,7,Donated on 10/5/2019
5,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,Donated on 4/30/1996
6,Raisin,Multivariate,Classification,"Real, Integer",900,7,Donated on 8/13/2023
7,PhiUSIIL Phishing URL (Website),Tabular,Classification,"Real, Categorical, Integer",235795,54,Donated on 3/3/2024
8,RT-IoT2022,"Tabular, Sequential, Multivariate","Classification, Regression, Clustering","Real, Categorical",123117,83,Donated on 1/4/2024
9,Regensburg Pediatric Appendicitis,"Tabular, Image",Classification,"Real, Categorical, Integer",782,53,Linked on 12/6/2023
10,National Poll on Healthy Aging (NPHA),Tabular,Classification,Categorical,714,14,Donated on 12/5/2023
11,Infrared Thermography Temperature,Tabular,Regression,"Real, Categorical",1020,33,Linked on 11/20/2023
12,Jute Pest,Image,"Classification, Other",Categorical,7235,17,Donated on 11/17/2023